// app/build.gradle (Módulo de la aplicación)
plugins {
    id 'com.android.application'
}

android {
    // Pon aquí el nombre de paquete que quieras para tu App
    namespace 'com.ejemplo.misdl3'
    compileSdk 34

    defaultConfig {
        applicationId "com.ejemplo.misdl3"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // Vincula el archivo AAR de SDL3 que pusiste en app/libs/
    implementation files('libs/SDL3-3.4.16.aar')

    // Dependencias mínimas de Android para levantar la interfaz nativa
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
