plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wow.client'
    compileSdk 34

    defaultConfig {
        applicationId "com.wow.client"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    signingConfigs {
        release {
            // Se vincula con la llave wow-auto-key.keystore que genera tu acción de GitHub
            storeFile file('wow-auto-key.keystore')
            storePassword "WowPassword123"
            keyAlias "wowalias"
            keyPassword "WowPassword123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}
