name: Compilar APK WoW Movil
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Compilar APK con el Motor Automatizado Oficial
        uses: ArtemGovorov/action-buildozer@v1.3.0
        with:
          command: android debug
