name: Build Android App with SDL3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo fuente del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17 Estable
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Autogenerar archivos del Gradle Wrapper de forma Nativa
      # Reemplazamos wget por un comando que fabrica el .jar localmente en el servidor
      run: gradle wrapper --gradle-version 8.2
      working-directory: ./mi-proyecto

    - name: Otorgar permisos de ejecucion al script gradlew
      run: chmod +x ./gradlew
      working-directory: ./mi-proyecto

    - name: Compilar APK Nativa con Gradle
      run: ./gradlew assembleDebug
      working-directory: ./mi-proyecto

    - name: Subir APK de SDL3 para Descargar
      uses: actions/upload-artifact@v4
      with:
        name: WoW-SDL3-Mobile-APK
        path: mi-proyecto/app/build/outputs/apk/debug/*.apk
