name: Compilar APK WoW Movil
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar Java 17 Estable
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar e Instalar Android SDK Oficial en el Servidor
        uses: android-actions/setup-android@v3

      - name: Compilar APK con Inyeccion de SDK Nativo
        run: |
          # Creamos la carpeta base para que Docker guarde los temporales
          mkdir -p .buildozer
          
          # Lanzamos el contenedor compartiendo el SDK oficial que instalo GitHub arriba
          echo "y" | docker run --rm \
            -v "${{ github.workspace }}":/home/user/app \
            -v "${{ github.workspace }}/.buildozer":/home/user/.buildozer \
            -v "/usr/local/lib/android/sdk":/home/user/.buildozer/android/platform/android-sdk \
            -w /home/user/app \
            -i \
            kivy/buildozer:latest android debug
